package com.gs.hibernate.models;
// Generated 19 Jul, 2019 8:29:04 PM by Hibernate Tools 5.2.10.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.ManyToMany;
import javax.persistence.Table;

/**
 * CustomerDemographics generated by hbm2java
 */
@Entity
@Table(name = "customer_demographics", schema = "public")
public class CustomerDemographics implements java.io.Serializable {

	private String customerTypeId;
	private String customerDesc;
	private Set<Customers> customerses = new HashSet<Customers>(0);

	public CustomerDemographics() {
	}

	public CustomerDemographics(String customerTypeId) {
		this.customerTypeId = customerTypeId;
	}

	public CustomerDemographics(String customerTypeId, String customerDesc, Set<Customers> customerses) {
		this.customerTypeId = customerTypeId;
		this.customerDesc = customerDesc;
		this.customerses = customerses;
	}

	@Id

	@Column(name = "customer_type_id", unique = true, nullable = false)
	public String getCustomerTypeId() {
		return this.customerTypeId;
	}

	public void setCustomerTypeId(String customerTypeId) {
		this.customerTypeId = customerTypeId;
	}

	@Column(name = "customer_desc")
	public String getCustomerDesc() {
		return this.customerDesc;
	}

	public void setCustomerDesc(String customerDesc) {
		this.customerDesc = customerDesc;
	}

	@ManyToMany(fetch = FetchType.LAZY, mappedBy = "customerDemographicses")
	public Set<Customers> getCustomerses() {
		return this.customerses;
	}

	public void setCustomerses(Set<Customers> customerses) {
		this.customerses = customerses;
	}

}
