package com.gs.hibernate.models;
// Generated 19 Jul, 2019 8:29:04 PM by Hibernate Tools 5.2.10.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Region generated by hbm2java
 */
@Entity
@Table(name = "region", schema = "public")
public class Region implements java.io.Serializable {

	private short regionId;
	private String regionDescription;
	private Set<Territories> territorieses = new HashSet<Territories>(0);

	public Region() {
	}

	public Region(short regionId, String regionDescription) {
		this.regionId = regionId;
		this.regionDescription = regionDescription;
	}

	public Region(short regionId, String regionDescription, Set<Territories> territorieses) {
		this.regionId = regionId;
		this.regionDescription = regionDescription;
		this.territorieses = territorieses;
	}

	@Id

	@Column(name = "region_id", unique = true, nullable = false)
	public short getRegionId() {
		return this.regionId;
	}

	public void setRegionId(short regionId) {
		this.regionId = regionId;
	}

	@Column(name = "region_description", nullable = false)
	public String getRegionDescription() {
		return this.regionDescription;
	}

	public void setRegionDescription(String regionDescription) {
		this.regionDescription = regionDescription;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "region")
	public Set<Territories> getTerritorieses() {
		return this.territorieses;
	}

	public void setTerritorieses(Set<Territories> territorieses) {
		this.territorieses = territorieses;
	}

}
