package com.gs.hibernate.models;
// Generated 19 Jul, 2019 8:29:04 PM by Hibernate Tools 5.2.10.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Shippers generated by hbm2java
 */
@Entity
@Table(name = "shippers", schema = "public")
public class Shippers implements java.io.Serializable {

	private short shipperId;
	private String companyName;
	private String phone;
	private Set<Orders> orderses = new HashSet<Orders>(0);

	public Shippers() {
	}

	public Shippers(short shipperId, String companyName) {
		this.shipperId = shipperId;
		this.companyName = companyName;
	}

	public Shippers(short shipperId, String companyName, String phone, Set<Orders> orderses) {
		this.shipperId = shipperId;
		this.companyName = companyName;
		this.phone = phone;
		this.orderses = orderses;
	}

	@Id

	@Column(name = "shipper_id", unique = true, nullable = false)
	public short getShipperId() {
		return this.shipperId;
	}

	public void setShipperId(short shipperId) {
		this.shipperId = shipperId;
	}

	@Column(name = "company_name", nullable = false, length = 40)
	public String getCompanyName() {
		return this.companyName;
	}

	public void setCompanyName(String companyName) {
		this.companyName = companyName;
	}

	@Column(name = "phone", length = 24)
	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "shippers")
	public Set<Orders> getOrderses() {
		return this.orderses;
	}

	public void setOrderses(Set<Orders> orderses) {
		this.orderses = orderses;
	}

}
