package com.gs.hibernate.models;
// Generated 19 Jul, 2019 8:29:04 PM by Hibernate Tools 5.2.10.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Standard generated by hbm2java
 */
@Entity
@Table(name = "standard", schema = "public")
public class Standard implements java.io.Serializable {

	private long seq;
	private int numofstundents;
	private String sname;
	private Set<TeacherStandard> teacherStandards = new HashSet<TeacherStandard>(0);

	public Standard() {
	}

	public Standard(long seq, int numofstundents) {
		this.seq = seq;
		this.numofstundents = numofstundents;
	}

	public Standard(long seq, int numofstundents, String sname, Set<TeacherStandard> teacherStandards) {
		this.seq = seq;
		this.numofstundents = numofstundents;
		this.sname = sname;
		this.teacherStandards = teacherStandards;
	}

	@Id

	@Column(name = "seq", unique = true, nullable = false)
	public long getSeq() {
		return this.seq;
	}

	public void setSeq(long seq) {
		this.seq = seq;
	}

	@Column(name = "numofstundents", nullable = false)
	public int getNumofstundents() {
		return this.numofstundents;
	}

	public void setNumofstundents(int numofstundents) {
		this.numofstundents = numofstundents;
	}

	@Column(name = "sname")
	public String getSname() {
		return this.sname;
	}

	public void setSname(String sname) {
		this.sname = sname;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "standard")
	public Set<TeacherStandard> getTeacherStandards() {
		return this.teacherStandards;
	}

	public void setTeacherStandards(Set<TeacherStandard> teacherStandards) {
		this.teacherStandards = teacherStandards;
	}

}
