package com.gs.hibernate.models;
// Generated 19 Jul, 2019 8:29:04 PM by Hibernate Tools 5.2.10.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * TeacherStandard generated by hbm2java
 */
@Entity
@Table(name = "teacher_standard", schema = "public")
public class TeacherStandard implements java.io.Serializable {

	private TeacherStandardId id;
	private Standard standard;
	private Teacher teacher;

	public TeacherStandard() {
	}

	public TeacherStandard(TeacherStandardId id, Standard standard, Teacher teacher) {
		this.id = id;
		this.standard = standard;
		this.teacher = teacher;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "teachersSeq", column = @Column(name = "teachers_seq", nullable = false)),
			@AttributeOverride(name = "standardsSeq", column = @Column(name = "standards_seq", nullable = false)) })
	public TeacherStandardId getId() {
		return this.id;
	}

	public void setId(TeacherStandardId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "standards_seq", nullable = false, insertable = false, updatable = false)
	public Standard getStandard() {
		return this.standard;
	}

	public void setStandard(Standard standard) {
		this.standard = standard;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "teachers_seq", nullable = false, insertable = false, updatable = false)
	public Teacher getTeacher() {
		return this.teacher;
	}

	public void setTeacher(Teacher teacher) {
		this.teacher = teacher;
	}

}
