package com.gs.hibernate.models;
// Generated 19 Jul, 2019 8:29:04 PM by Hibernate Tools 5.2.10.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Ticket generated by hbm2java
 */
@Entity
@Table(name = "ticket", schema = "public")
public class Ticket implements java.io.Serializable {

	private long seq;
	private PassengerTable passengerTable;
	private Date date2;
	private Date date3;
	private Date date4;
	private double price;
	private String ticketName;

	public Ticket() {
	}

	public Ticket(long seq, double price) {
		this.seq = seq;
		this.price = price;
	}

	public Ticket(long seq, PassengerTable passengerTable, Date date2, Date date3, Date date4, double price,
			String ticketName) {
		this.seq = seq;
		this.passengerTable = passengerTable;
		this.date2 = date2;
		this.date3 = date3;
		this.date4 = date4;
		this.price = price;
		this.ticketName = ticketName;
	}

	@Id

	@Column(name = "seq", unique = true, nullable = false)
	public long getSeq() {
		return this.seq;
	}

	public void setSeq(long seq) {
		this.seq = seq;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "pass_id")
	public PassengerTable getPassengerTable() {
		return this.passengerTable;
	}

	public void setPassengerTable(PassengerTable passengerTable) {
		this.passengerTable = passengerTable;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "date2", length = 13)
	public Date getDate2() {
		return this.date2;
	}

	public void setDate2(Date date2) {
		this.date2 = date2;
	}

	@Temporal(TemporalType.TIME)
	@Column(name = "date3", length = 15)
	public Date getDate3() {
		return this.date3;
	}

	public void setDate3(Date date3) {
		this.date3 = date3;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "date4", length = 29)
	public Date getDate4() {
		return this.date4;
	}

	public void setDate4(Date date4) {
		this.date4 = date4;
	}

	@Column(name = "price", nullable = false, precision = 17, scale = 17)
	public double getPrice() {
		return this.price;
	}

	public void setPrice(double price) {
		this.price = price;
	}

	@Column(name = "ticket_name")
	public String getTicketName() {
		return this.ticketName;
	}

	public void setTicketName(String ticketName) {
		this.ticketName = ticketName;
	}

}
